spring:
  application:
    name: spring-boot-sheduler
  datasource:
    username: sa
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    password:
  h2:
    console:
      enabled: 'true'
      settings:
        web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect